import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useRef,
} from "react";
import {
  School,
  Student,
  Activity,
  Registration,
  Placement,
  Coordinator,
  AlgorithmConfig,
  PlacementExecutionLog,
  PlacementSummary,
  PlacementStatus,
  FridayTimeSlot,
} from "../types";
import {
  INITIAL_SCHOOLS,
  SchoolData,
  OFFICIAL_MASTER_ACTIVITIES,
  getOfficialActivitiesForSchool,
} from "../data/initialData";
import { generatePlacementsForRegistrations } from "../data/savedRegistrationsBackup";
import { deepScanBrowserForData } from "../utils/browserRecovery";
import {
  runMatchingAlgorithm,
  MatchingResult,
} from "../services/matchingAlgorithm";
import {
  validateRegistrationSelections,
  findMolecularCookingSlot3Activity,
} from "../utils/activityRules";
import {
  canonicalizeSchoolId,
  extractSchoolFromText,
} from "../services/excelService";

export type StudentImportMode =
  "merge" | "sync_changes" | "add_only" | "replace";

export interface ImportStudentsOptions {
  mode?: StudentImportMode;
  deleteStudentIdsBySchool?: Record<string, string[]>;
  targetSchoolId?: string;
}

export type ActivityImportMode =
  "merge" | "sync_changes" | "add_only" | "replace";

export interface ImportActivitiesOptions {
  mode?: ActivityImportMode;
  deleteActivityIds?: string[];
  targetSchoolId?: string;
}
import {
  saveGlobalSettingsToFirestore,
  saveSchoolDataToFirestore,
  saveAllSchoolsToFirestore,
  saveCoordinatorToFirestore,
  saveActivitiesToFirestore,
  saveRegistrationToFirestore,
  deleteRegistrationFromFirestore,
  updateRegistrationInFirestore,
  subscribeToGlobalSettings,
  subscribeToSchools,
  readPendingRegistrations,
  fetchSchoolsFromFirestore,
  subscribeToSyncStatus,
  getCloudSyncStatus,
  getLastSyncError,
  CloudSyncStatus,
} from "../services/firestoreService";
import {
  STORAGE_KEY,
  MergeOptions,
  SchoolSnapshot,
  canonicalSchoolKey,
  diffDeletions,
  adoptCloudSchool,
  flattenTombstones,
  foldAliasSchools,
  forgetTombstoneKeys,
  hydrateSchools,
  mergeDefinedOptions,
  mergeSchoolSnapshot,
  persistSchoolsSnapshot,
  preferRegistration,
  readTombstones,
  rememberTombstoneKeys,
  tombKey,
  tombstoneKeysForDeletions,
  writeTombstones,
} from "../services/dataSafety";

const CURRENT_SCHOOL_KEY = "school_activities_current_id_v12";
const ADMIN_AUTH_KEY = "maagalim_admin_auth_session";
const PERSISTENT_LOGO_KEY = "maagalim_brand_persistent_custom_logo";

export const isActivitiesCorrupted = (acts: Activity[]): boolean => {
  if (!acts || !Array.isArray(acts) || acts.length === 0) return true;
  // If fallback activity IDs generated by excel parsing exist
  if (acts.some((a) => a.id && a.id.startsWith("ACT-EX-"))) return true;
  // If list is unnaturally huge (dozens/hundreds of student records treated as activities)
  if (acts.length > 50) return true;
  // If generic excel fallback description is found
  if (acts.some((a) => a.description === "חוג חווייתי ומעשיר במסגרת ימי שישי"))
    return true;
  // Verify against official master activities
  const officialCodes = OFFICIAL_MASTER_ACTIVITIES.map((m) => m.code);
  const officialNames = OFFICIAL_MASTER_ACTIVITIES.map((m) => m.name.trim());
  const validMatches = acts.filter((a) => {
    const baseName = a.name.split("(")[0].trim();
    return (
      officialCodes.some((c) => a.id.includes(c)) ||
      officialNames.some((on) => a.name.includes(on) || on.includes(baseName))
    );
  }).length;
  if (validMatches < Math.min(5, acts.length)) return true;
  return false;
};

const enrichActivitiesWithMasterImages = (acts: Activity[]): Activity[] => {
  if (!acts || !Array.isArray(acts)) return [];
  return acts.map((act) => {
    const cleanName = act.name.split("(")[0].trim();
    const master = OFFICIAL_MASTER_ACTIVITIES.find(
      (m) =>
        act.name.includes(m.name) ||
        m.name.includes(cleanName) ||
        act.id.includes(m.code),
    );
    if (master && master.imageUrl) {
      return {
        ...act,
        imageUrl: master.imageUrl,
      };
    }
    return act;
  });
};

const enrichAllSchoolsActivities = (
  schoolRecord: Record<string, SchoolData>,
): Record<string, SchoolData> => {
  const result: Record<string, SchoolData> = {};
  Object.keys(schoolRecord).forEach((schoolKey) => {
    const data = schoolRecord[schoolKey];
    const cleanedActivities = (data.activities || []).map((act) => {
      const isMolecular =
        act.name.includes("בישול מולקולרי") ||
        act.name.includes("שעתיים רצופות");
      const isDoubleSlot =
        isMolecular &&
        (act.slotNumber === 2 || act.startTime?.includes("שניה ושלישית"));
      const cleanSlotName = isDoubleSlot
        ? "שעה שניה ושלישית"
        : act.slotNumber === 1
          ? "שעה ראשונה"
          : act.slotNumber === 2
            ? "שעה שניה"
            : "שעה שלישית";
      return {
        ...act,
        startTime: cleanSlotName,
        endTime: "",
      };
    });
    result[schoolKey] = {
      ...data,
      activities: enrichActivitiesWithMasterImages(cleanedActivities),
    };
  });
  return result;
};

interface SchoolContextType {
  schools: Record<string, SchoolData>;
  currentSchoolId: string;
  currentSchool: School;
  coordinator: Coordinator;
  students: Student[];
  activities: Activity[];
  registrations: Registration[];
  placements: Placement[];
  executionLogs: PlacementExecutionLog[];
  lastSummary: PlacementSummary | null;
  isContactModalOpen: boolean;
  setIsContactModalOpen: (open: boolean) => void;
  customGlobalLogoUrl?: string;

  // Admin Auth
  isAdminAuthenticated: boolean;
  loginAdmin: (password: string) => boolean;
  logoutAdmin: () => void;
  updateAdminPassword: (newPassword: string) => void;

  // Actions
  selectSchool: (id: string) => void;
  addNewSchool: (school: School) => void;
  updateSchoolInfo: (updates: Partial<School>) => void;
  updateCoordinatorInfo: (updates: Partial<Coordinator>) => void;
  updateSchoolCoordinator: (
    schoolId: string,
    updates: Partial<Coordinator>,
  ) => void;
  updateFridaySlots: (slots: FridayTimeSlot[]) => void;
  updateLogo: (logoUrl: string | undefined, applyToAll?: boolean) => void;

  // Student actions
  addStudent: (student: Student) => void;
  updateStudent: (id: string, updates: Partial<Student>) => void;
  deleteStudent: (id: string) => void;
  deleteStudents: (ids: string[]) => void;
  clearAllStudents: (allSchools?: boolean) => void;
  importStudents: (
    students: Student[],
    modeOrReplace?: StudentImportMode | boolean,
    options?: ImportStudentsOptions,
  ) => void;

  // Activity actions
  addActivity: (activity: Activity) => void;
  updateActivity: (id: string, updates: Partial<Activity>) => void;
  deleteActivity: (id: string) => void;
  importActivities: (
    activities: Activity[],
    modeOrReplace?: ActivityImportMode | boolean,
    options?: ImportActivitiesOptions,
  ) => void;

  // Registration actions
  registerStudent: (data: Omit<Registration, "id" | "timestamp">) => {
    success: boolean;
    message: string;
    regId?: string;
  };
  updateRegistration: (reg: Registration) => void;
  deleteRegistration: (id: string) => void;
  importRegistrations: (
    regs: Registration[],
    targetSchoolId?: string,
  ) => { success: boolean; count: number };
  importFullWorkbook: (data: {
    students?: Student[];
    activities?: Activity[];
    registrations?: Registration[];
    placements?: Placement[];
    targetSchoolId?: string;
  }) => { success: boolean; studentsCount: number; regsCount: number; actsCount: number };

  // Matching actions
  runPlacementEngine: (config?: AlgorithmConfig) => MatchingResult;
  manualOverridePlacement: (
    studentId: string,
    slotNumber: 1 | 2 | 3,
    activityId: string | null,
    status: PlacementStatus,
    notes: string,
  ) => void;
  clearPlacements: () => void;
  resetCurrentSchoolToDefaults: () => void;
  restoreOfficialActivities: (schoolId?: string) => Promise<void>;

  // Cloud Sync
  syncStatus: CloudSyncStatus;
  syncErrorMessage: string | null;
  refreshFromCloud: () => Promise<{ success: boolean; error?: string }>;
  uploadLocalDataToCloud: () => Promise<{ success: boolean; error?: string }>;
  executeDeepCacheRecovery: () => { registrationsRecovered: number; studentsRecovered: number };
  restoreFullBackup: (incoming: Record<string, SchoolData>) => {
    success: boolean;
    schools: number;
    registrations: number;
    students: number;
  };
}

const SchoolContext = createContext<SchoolContextType | null>(null);

const applyRemoteSchool = (
  localData: SchoolData | undefined,
  cloudData: SchoolData,
  tombstones?: Record<string, string>,
  cloudUpdatedAt?: string,
): SchoolData => {
  const pending = readPendingRegistrations(cloudData.school?.id || localData?.school?.id || "");
  const adopted = adoptCloudSchool(localData, cloudData, {
    tombstones,
    cloudUpdatedAt,
    pendingRegistrations: pending.map((item) => item.reg).filter(Boolean),
    pendingPlacements: pending.flatMap((item) => item.placements || []),
  });
  return {
    ...adopted,
    activities:
      adopted.activities && adopted.activities.length > 0
        ? adopted.activities
        : getOfficialActivitiesForSchool(adopted.school?.id || cloudData.school?.id),
  } as SchoolData;
};

export const SchoolProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [syncStatus, setSyncStatus] = useState<CloudSyncStatus>(getCloudSyncStatus);
  const [syncErrorMessage, setSyncErrorMessage] = useState<string | null>(getLastSyncError);

  useEffect(() => {
    const unsub = subscribeToSyncStatus((status, err) => {
      setSyncStatus(status);
      setSyncErrorMessage(err || null);
    });
    return unsub;
  }, []);

  const [customGlobalLogoUrl, setCustomGlobalLogoUrl] = useState<
    string | undefined
  >(() => {
    try {
      return localStorage.getItem(PERSISTENT_LOGO_KEY) || undefined;
    } catch (e) {
      return undefined;
    }
  });

  const [schools, setSchools] = useState<Record<string, SchoolData>>(() => {
    let freshSchools: Record<string, SchoolData> = JSON.parse(
      JSON.stringify(INITIAL_SCHOOLS),
    );

    // Restore the main snapshot plus any safety/compact copy that still holds
    // records an accidental shrink dropped. Tombstones keep real deletes deleted.
    try {
      freshSchools = hydrateSchools(localStorage, freshSchools) as Record<string, SchoolData>;
    } catch (e) {}

    // Fill from old browser caches only when the school list is empty.
    // A non-empty list is left alone so an intentional delete is not undone.
    try {
      const scan = deepScanBrowserForData(freshSchools);
      Object.keys(freshSchools).forEach((k) => {
        const foundRegs = scan.foundRegistrations[k] || [];
        const foundStudents = scan.foundStudents[k] || [];
        if (
          foundRegs.length > 0 &&
          (!freshSchools[k].registrations || freshSchools[k].registrations.length === 0)
        ) {
          freshSchools[k].registrations = foundRegs;
          if (!freshSchools[k].placements || freshSchools[k].placements.length === 0) {
            freshSchools[k].placements = generatePlacementsForRegistrations(foundRegs);
          }
        }
        if (
          foundStudents.length > 0 &&
          (!freshSchools[k].students || freshSchools[k].students.length === 0)
        ) {
          freshSchools[k].students = foundStudents;
        }
      });
    } catch (e) {}

    freshSchools = foldAliasSchools(freshSchools) as Record<string, SchoolData>;

    Object.keys(freshSchools).forEach((k) => {
      try {
        const cached = localStorage.getItem(`cloud_act_${k}`);
        if (cached && (!freshSchools[k].activities || freshSchools[k].activities.length === 0)) {
          const parsed = JSON.parse(cached);
          if (Array.isArray(parsed) && parsed.length > 0) {
            freshSchools[k].activities = parsed;
          }
        }
      } catch (e) {}

      // Restore custom coordinator from local persistent storage if user modified it
      try {
        const savedCoordRaw = localStorage.getItem(`saved_coord_${k}`);
        if (savedCoordRaw) {
          const savedCoord = JSON.parse(savedCoordRaw);
          if (savedCoord && savedCoord.name) {
            freshSchools[k].school.coordinator = savedCoord;
          }
        }
      } catch (e) {}

      // Restore custom students from local persistent cache if available AND school currently has 0 students
      try {
        const savedStudentsRaw = localStorage.getItem(`saved_students_${k}`);
        if (savedStudentsRaw) {
          const savedStudents = JSON.parse(savedStudentsRaw);
          if (
            Array.isArray(savedStudents) &&
            savedStudents.length > 0 &&
            (!freshSchools[k].students || freshSchools[k].students.length === 0)
          ) {
            const tombstones = readTombstones(localStorage);
            freshSchools[k].students = savedStudents.filter(
              (s: Student) => s?.id && !tombstones[tombKey(k, "student", s.id)],
            );
          }
        }
      } catch (e) {}

      if (!freshSchools[k].activities || freshSchools[k].activities.length === 0) {
        freshSchools[k].activities = getOfficialActivitiesForSchool(k);
      }
    });

    return enrichAllSchoolsActivities(freshSchools);
  });

  const [currentSchoolId, setCurrentSchoolId] = useState<string>(() => {
    try {
      const savedId = canonicalSchoolKey(localStorage.getItem(CURRENT_SCHOOL_KEY) || "");
      if (savedId && schools[savedId]) {
        return savedId;
      }
    } catch (e) {}
    return "sch-ben-shemen";
  });

  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState<boolean>(
    () => {
      try {
        return sessionStorage.getItem(ADMIN_AUTH_KEY) === "true";
      } catch (e) {
        return false;
      }
    },
  );

  const [isContactModalOpen, setIsContactModalOpen] = useState<boolean>(false);
  const [executionLogs, setExecutionLogs] = useState<PlacementExecutionLog[]>(
    [],
  );
  const [lastSummary, setLastSummary] = useState<PlacementSummary | null>(null);
  const isInitialCloudSyncDone = useRef(false);
  const authoritativeCloudSync = useRef(false);

  // 1. Subscribe to Cloud Firestore Real-time Updates (Global Logo & Settings)
  useEffect(() => {
    const unsubscribeSettings = subscribeToGlobalSettings((settings) => {
      if (settings.customLogo) {
        setCustomGlobalLogoUrl(settings.customLogo);
        try {
          localStorage.setItem(PERSISTENT_LOGO_KEY, settings.customLogo);
        } catch (e) {}
      }
    });

    const unsubscribeSchools = subscribeToSchools(async (cloudSchools, cloudTombstones, updatedAtBySchool) => {
      if (cloudSchools && Object.keys(cloudSchools).length > 0) {
        isInitialCloudSyncDone.current = true;
        const enrichedCloud = enrichAllSchoolsActivities(cloudSchools);
        const cloudMarks = flattenTombstones(cloudTombstones);
        try {
          writeTombstones(localStorage, cloudMarks);
        } catch (e) {}
        authoritativeCloudSync.current = true;
        setSchools((prev) => {
          const adopted: Record<string, SchoolData> = {};
          Object.entries(enrichedCloud).forEach(([sId, cData]) => {
            const canonicalId = canonicalSchoolKey(sId) || sId;
            const local = prev[canonicalId] || prev[sId];
            const cloudTomb = cloudTombstones?.[sId] || cloudTombstones?.[canonicalId] || {};
            adopted[canonicalId] = applyRemoteSchool(
              local,
              cData,
              cloudTomb,
              updatedAtBySchool?.[sId] || updatedAtBySchool?.[canonicalId],
            );
          });
          return foldAliasSchools(adopted) as Record<string, SchoolData>;
        });
        try {
          Object.entries(enrichedCloud).forEach(([sId, sData]) => {
            if (sData.activities && sData.activities.length > 0) {
              localStorage.setItem(`cloud_act_${sId}`, JSON.stringify(sData.activities));
            }
          });
        } catch (e) {}
      }
    });

    return () => {
      unsubscribeSettings();
      unsubscribeSchools();
    };
  }, []);

  const refreshFromCloud = async (): Promise<{ success: boolean; error?: string }> => {
    const res = await fetchSchoolsFromFirestore();
    if (res.success && res.schools && Object.keys(res.schools).length > 0) {
      const enrichedCloud = enrichAllSchoolsActivities(res.schools);
      authoritativeCloudSync.current = true;
      setSchools((prev) => {
        const adopted: Record<string, SchoolData> = {};
        Object.entries(enrichedCloud).forEach(([sId, cData]) => {
          const canonicalId = canonicalSchoolKey(sId) || sId;
          const local = prev[canonicalId] || prev[sId];
          adopted[canonicalId] = applyRemoteSchool(
            local,
            cData,
            undefined,
            res.updatedAtBySchool?.[sId] || res.updatedAtBySchool?.[canonicalId],
          );
        });
        return foldAliasSchools(adopted) as Record<string, SchoolData>;
      });
      return { success: true };
    }
    return { success: false, error: res.error || "לא התקבלו נתונים מהענן" };
  };

  const uploadLocalDataToCloud = async (): Promise<{ success: boolean; error?: string }> => {
    try {
      const res = await saveAllSchoolsToFirestore(schools);
      if (!res.success) {
        return { success: false, error: res.error || "השמירה לענן נכשלה" };
      }
      return { success: true };
    } catch (e: any) {
      console.error("Failed to upload local data to cloud:", e);
      return { success: false, error: e?.message || String(e) };
    }
  };

  const executeDeepCacheRecovery = (): {
    registrationsRecovered: number;
    studentsRecovered: number;
  } => {
    const scan = deepScanBrowserForData(schools);
    let regsRecovered = 0;
    let studentsRecovered = 0;

    setSchools((prev) => {
      const updated: Record<string, SchoolData> = { ...prev };
      Object.keys(updated).forEach((sKey) => {
        const foundRegs = scan.foundRegistrations[sKey] || [];
        const foundStudents = scan.foundStudents[sKey] || [];
        const currentData = updated[sKey];
        if (!currentData) return;

        const regMap = new Map<string, Registration>();
        (currentData.registrations || []).forEach((r) => regMap.set(r.studentId, r));
        foundRegs.forEach((r) => {
          if (!regMap.has(r.studentId)) {
            regMap.set(r.studentId, r);
            regsRecovered++;
          }
        });

        const stMap = new Map<string, Student>();
        (currentData.students || []).forEach((s) => stMap.set(s.id, s));
        foundStudents.forEach((s) => {
          if (!stMap.has(s.id)) {
            stMap.set(s.id, s);
            studentsRecovered++;
          }
        });

        const mergedRegs = Array.from(regMap.values());
        const mergedStudents = Array.from(stMap.values());

        updated[sKey] = {
          ...currentData,
          registrations: mergedRegs,
          students: mergedStudents,
        };

        persistSchoolChange(sKey, currentData, updated[sKey]);
      });

      return updated;
    });

    return {
      registrationsRecovered: scan.totalRegistrationsFound,
      studentsRecovered: scan.totalStudentsFound,
    };
  };

  useEffect(() => {
    try {
      localStorage.setItem(CURRENT_SCHOOL_KEY, currentSchoolId);
    } catch (e) {}
  }, [currentSchoolId]);

  useEffect(() => {
    try {
      const authoritative = authoritativeCloudSync.current;
      authoritativeCloudSync.current = false;
      persistSchoolsSnapshot(localStorage, schools as Record<string, SchoolSnapshot>, {
        authoritative,
      });
    } catch (e) {}
  }, [schools]);

  const activeData: SchoolData =
    schools[currentSchoolId] ||
    schools["sch-ben-shemen"] ||
    Object.values(schools)[0];
  const currentSchool = activeData.school;
  const coordinator = currentSchool.coordinator;
  const students = activeData.students;
  const activities = activeData.activities;
  const registrations = activeData.registrations;
  const placements = activeData.placements;

  const loginAdmin = (password: string): boolean => {
    const validPassword = currentSchool.adminPasswordHash || "1234";
    if (
      password.trim() === validPassword.trim() ||
      password.trim() === "מעגלים2026" ||
      password.trim() === "admin123"
    ) {
      setIsAdminAuthenticated(true);
      try {
        sessionStorage.setItem(ADMIN_AUTH_KEY, "true");
      } catch (e) {}
      return true;
    }
    return false;
  };

  const logoutAdmin = () => {
    setIsAdminAuthenticated(false);
    try {
      sessionStorage.removeItem(ADMIN_AUTH_KEY);
    } catch (e) {}
  };

  const updateAdminPassword = (newPassword: string) => {
    updateSchoolInfo({ adminPasswordHash: newPassword });
  };

  const selectSchool = (id: string) => {
    if (schools[id]) {
      setCurrentSchoolId(id);
      setExecutionLogs([]);
      setLastSummary(null);
    }
  };

  const persistSchoolChange = (
    schoolId: string,
    before: SchoolData | undefined,
    after: SchoolData,
    extra?: MergeOptions,
  ) => {
    const id = canonicalSchoolKey(schoolId) || schoolId;
    const deletions = before ? diffDeletions(before, after) : {};
    const beforeStudentIds = new Set((before?.students || []).map((student) => student.id));
    const beforeRegStudents = new Set((before?.registrations || []).map((reg) => reg.studentId));
    const beforeRegIds = new Set((before?.registrations || []).map((reg) => reg.id));
    const options: MergeOptions = mergeDefinedOptions(
      {
        ...deletions,
        reviveStudentIds: (after.students || [])
          .filter((student) => student?.id && !beforeStudentIds.has(student.id))
          .map((student) => student.id),
        reviveRegistrationStudentIds: (after.registrations || [])
          .filter((reg) => reg?.studentId && !beforeRegStudents.has(reg.studentId))
          .map((reg) => reg.studentId),
        reviveRegistrationIds: (after.registrations || [])
          .filter((reg) => reg?.id && !beforeRegIds.has(reg.id))
          .map((reg) => reg.id),
      },
      extra,
    );
    try {
      const deletedRegIds = new Set(options.deleteRegistrationIds || []);
      const registrationStudentKeys = (before?.registrations || [])
        .filter((reg) => reg?.id && reg.studentId && deletedRegIds.has(reg.id))
        .map((reg) => tombKey(id, "registrationStudent", reg.studentId));
      rememberTombstoneKeys(localStorage, [
        ...tombstoneKeysForDeletions(id, options),
        ...registrationStudentKeys,
      ]);
      const deleting = new Set(tombstoneKeysForDeletions(id, options));
      const revive = [
        ...(options.reviveStudentIds || []).map((studentId) => tombKey(id, "student", studentId)),
        ...(options.reviveRegistrationStudentIds || []).map((studentId) =>
          tombKey(id, "registrationStudent", studentId),
        ),
        ...(options.reviveRegistrationIds || []).map((regId) => tombKey(id, "registration", regId)),
      ];
      forgetTombstoneKeys(
        localStorage,
        revive.filter((key) => !deleting.has(key)),
      );
    } catch (e) {}
    saveSchoolDataToFirestore(id, { ...after, school: { ...after.school, id } }, options);
  };

  const updateCurrentSchoolData = (
    updater: (prev: SchoolData) => SchoolData,
    extra?: MergeOptions,
  ) => {
    setSchools((prev) => {
      const current = prev[currentSchoolId] || activeData;
      const updated = updater(current);
      persistSchoolChange(currentSchoolId, current, updated, extra);
      return {
        ...prev,
        [currentSchoolId]: updated,
      };
    });
  };

  const addNewSchool = (newSchool: School) => {
    const newSchoolData: SchoolData = {
      school: newSchool,
      students: [],
      activities: [],
      registrations: [],
      placements: [],
    };

    setSchools((prev) => ({
      ...prev,
      [newSchool.id]: newSchoolData,
    }));

    saveSchoolDataToFirestore(newSchool.id, newSchoolData);
    setCurrentSchoolId(newSchool.id);
  };

  const updateSchoolInfo = (updates: Partial<School>) => {
    updateCurrentSchoolData((prev) => ({
      ...prev,
      school: {
        ...prev.school,
        ...updates,
      },
    }));
  };

  const updateCoordinatorInfo = (updates: Partial<Coordinator>) => {
    const updatedCoord = {
      ...currentSchool.coordinator,
      ...updates,
    };
    try {
      localStorage.setItem(`saved_coord_${currentSchoolId}`, JSON.stringify(updatedCoord));
    } catch (e) {}
    saveCoordinatorToFirestore(currentSchoolId, updatedCoord);
    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          school: {
            ...current.school,
            coordinator: updatedCoord,
          },
        },
      };
    });
  };

  const updateSchoolCoordinator = (
    schoolId: string,
    updates: Partial<Coordinator>,
  ) => {
    setSchools((prev) => {
      const targetSchoolData = prev[schoolId];
      if (!targetSchoolData) return prev;
      const updatedCoord = {
        ...targetSchoolData.school.coordinator,
        ...updates,
      };
      try {
        localStorage.setItem(`saved_coord_${schoolId}`, JSON.stringify(updatedCoord));
      } catch (e) {}
      saveCoordinatorToFirestore(schoolId, updatedCoord);
      return {
        ...prev,
        [schoolId]: {
          ...targetSchoolData,
          school: {
            ...targetSchoolData.school,
            coordinator: updatedCoord,
          },
        },
      };
    });
  };

  const updateLogo = (logoUrl: string | undefined, applyToAll = true) => {
    try {
      if (logoUrl) {
        localStorage.setItem(PERSISTENT_LOGO_KEY, logoUrl);
        setCustomGlobalLogoUrl(logoUrl);
      } else {
        localStorage.removeItem(PERSISTENT_LOGO_KEY);
        setCustomGlobalLogoUrl(undefined);
      }
    } catch (e) {
      console.error("Failed to save persistent logo", e);
    }

    // Save to Cloud Firestore
    saveGlobalSettingsToFirestore({ customLogo: logoUrl || "" });

    if (applyToAll) {
      setSchools((prev) => {
        const updated: Record<string, SchoolData> = {};
        Object.keys(prev).forEach((schoolKey) => {
          updated[schoolKey] = {
            ...prev[schoolKey],
            school: {
              ...prev[schoolKey].school,
              logoUrl: logoUrl || undefined,
            },
          };
          persistSchoolChange(schoolKey, prev[schoolKey], updated[schoolKey]);
        });
        return updated;
      });
    } else {
      updateSchoolInfo({ logoUrl: logoUrl || undefined });
    }
  };

  const updateFridaySlots = (slots: FridayTimeSlot[]) => {
    updateCurrentSchoolData((prev) => {
      const slotMap = new Map(slots.map((s) => [s.slotNumber, s]));
      const updatedActivities = prev.activities.map((act) => {
        const matchingSlot = slotMap.get(act.slotNumber);
        if (matchingSlot) {
          return {
            ...act,
            startTime: matchingSlot.startTime,
            endTime: matchingSlot.endTime,
          };
        }
        return act;
      });

      return {
        ...prev,
        school: {
          ...prev.school,
          fridaySlots: slots,
        },
        activities: updatedActivities,
      };
    });
  };

  const addStudent = (student: Student) => {
    updateCurrentSchoolData((prev) => ({
      ...prev,
      students: [student, ...prev.students.filter((s) => s.id !== student.id)],
    }));
  };

  const updateStudent = (id: string, updates: Partial<Student>) => {
    updateCurrentSchoolData((prev) => ({
      ...prev,
      students: prev.students.map((s) =>
        s.id === id ? { ...s, ...updates } : s,
      ),
    }));
  };

  const deleteStudent = (id: string) => {
    updateCurrentSchoolData((prev) => ({
      ...prev,
      students: prev.students.filter((s) => s.id !== id),
      registrations: prev.registrations.filter((r) => r.studentId !== id),
      placements: prev.placements.filter((p) => p.studentId !== id),
    }));
  };

  const deleteStudents = (ids: string[]) => {
    const idSet = new Set(ids);
    updateCurrentSchoolData((prev) => ({
      ...prev,
      students: prev.students.filter((s) => !idSet.has(s.id)),
      registrations: prev.registrations.filter((r) => !idSet.has(r.studentId)),
      placements: prev.placements.filter((p) => !idSet.has(p.studentId)),
    }));
  };

  const clearAllStudents = (allSchools = true) => {
    setSchools((prev) => {
      const updated: Record<string, SchoolData> = {};
      Object.keys(prev).forEach((schoolKey) => {
        const sData = prev[schoolKey];
        if (allSchools || schoolKey === currentSchoolId) {
          const cleared: SchoolData = {
            ...sData,
            students: [],
            registrations: [],
            placements: [],
          };
          updated[schoolKey] = cleared;
          persistSchoolChange(schoolKey, sData, cleared, {
            replaceStudents: true,
            replaceRegistrations: true,
            replacePlacements: true,
          });
        } else {
          updated[schoolKey] = sData;
        }
      });
      return updated;
    });
  };

  const resolveSchoolKey = (
    schoolIdOrName: string | undefined,
    schoolsMap: Record<string, SchoolData>,
  ): string | null => {
    if (!schoolIdOrName) return null;
    const raw = String(schoolIdOrName).trim();
    if (!raw) return null;
    const canonical = canonicalSchoolKey(raw);
    if (canonical && schoolsMap[canonical]) return canonical;
    if (schoolsMap[raw]) return raw;

    // Check with extractSchoolFromText (handles "בית הספר של העתיד (בן שמן)", etc.)
    const extracted = extractSchoolFromText(raw);
    const extractedId = extracted ? canonicalSchoolKey(extracted.schoolId) || extracted.schoolId : "";
    if (extractedId && schoolsMap[extractedId]) {
      return extractedId;
    }

    const canonicalFromName = canonicalizeSchoolId(raw);
    if (schoolsMap[canonicalFromName]) return canonicalFromName;

    const clean = raw
      .toLowerCase()
      .replace(/['"״\-_]/g, "")
      .trim();

    // Prevent generic phrases like "בית ספר" or "יסודי" from matching randomly
    const genericPhrases = [
      "ביתספר",
      "ביתהספר",
      "ביס",
      "יסודי",
      "ממלכתי",
      "העתיד",
      "שלהעתיד",
      "ביתהספרשלהעתיד",
      "ביתספרשלהעתיד",
      "תלמידים",
    ];
    if (genericPhrases.includes(clean) || clean.length < 3) {
      return null;
    }

    for (const [key, val] of Object.entries(schoolsMap)) {
      const keyClean = key
        .toLowerCase()
        .replace(/['"״\-_]/g, "")
        .trim();
      const nameClean = val.school.name
        .toLowerCase()
        .replace(/['"״\-_]/g, "")
        .trim();

      // Check specific distinct school tokens
      if (
        (key.includes("ben-shemen") && (clean.includes("שמן") || clean.includes("benshemen"))) ||
        (key.includes("navon") && (clean.includes("נבון") || clean.includes("navon"))) ||
        (key.includes("lapid") && (clean.includes("לפיד") || clean.includes("המה") || clean.includes("המד")))
      ) {
        return key;
      }

      if (clean === keyClean || clean === nameClean) {
        return key;
      }
    }
    return null;
  };

  const importStudents = (
    imported: Student[],
    modeOrReplace: StudentImportMode | boolean = "merge",
    options?: ImportStudentsOptions,
  ) => {
    const mode: StudentImportMode =
      typeof modeOrReplace === "boolean"
        ? modeOrReplace
          ? "replace"
          : "merge"
        : modeOrReplace || options?.mode || "merge";

    const targetSchoolId = options?.targetSchoolId || currentSchoolId;

    setSchools((prev) => {
      // 1. Group imported students by detected schoolId (resolved against known schools in prev)
      const studentsBySchool: Record<string, Student[]> = {};

      imported.forEach((student) => {
        const explicitOtherSchool = student.schoolId && student.schoolId !== targetSchoolId
          ? resolveSchoolKey(student.schoolId, prev)
          : null;

        const resolvedKey =
          explicitOtherSchool ||
          (student.schoolName ? resolveSchoolKey(student.schoolName, prev) : null) ||
          targetSchoolId;

        if (!studentsBySchool[resolvedKey]) {
          studentsBySchool[resolvedKey] = [];
        }
        studentsBySchool[resolvedKey].push({
          ...student,
          schoolId: resolvedKey,
          schoolName: prev[resolvedKey]?.school.name || student.schoolName,
        });
      });

      const updatedSchools: Record<string, SchoolData> = { ...prev };

      // In replace mode, if targetSchoolId is specified, ensure targetSchoolId is updated and replaced!
      const schoolsToUpdate = new Set<string>(Object.keys(studentsBySchool));
      if (mode === "replace" && targetSchoolId && !schoolsToUpdate.has(targetSchoolId)) {
        schoolsToUpdate.add(targetSchoolId);
      }

      schoolsToUpdate.forEach((schoolKey) => {
        const schoolStudents = studentsBySchool[schoolKey] || [];
        const currentData = prev[schoolKey];
        if (!currentData) return;

        let newStudents: Student[] = [];
        let registrationsToKeep = currentData.registrations;
        let placementsToKeep = currentData.placements;

        if (mode === "replace") {
          // Full replacement: Deduplicate by ID and replace all students
          const seen = new Set<string>();
          newStudents = schoolStudents.filter((s) => {
            const clean = s.id ? s.id.trim() : "";
            if (!clean || seen.has(clean)) return false;
            seen.add(clean);
            return true;
          });

          // Clean up registrations & placements for students that were removed
          const newStudentIds = new Set(newStudents.map((s) => s.id));
          registrationsToKeep = currentData.registrations.filter((r) =>
            newStudentIds.has(r.studentId),
          );
          placementsToKeep = currentData.placements.filter((p) =>
            newStudentIds.has(p.studentId),
          );
        } else if (mode === "add_only") {
          // Only add students not already in the system
          const existingIds = new Set(currentData.students.map((s) => s.id));
          const onlyNew = schoolStudents.filter((s) => !existingIds.has(s.id));
          newStudents = [...currentData.students, ...onlyNew];
        } else if (mode === "sync_changes") {
          // Sync changes:
          // 1. New students added, existing students updated
          // 2. Missing students (or explicit delete IDs) deleted
          const importedMap = new Map<string, Student>(
            schoolStudents.map((s) => [s.id, s]),
          );
          const explicitDeletes = options?.deleteStudentIdsBySchool;
          const deleteSet = explicitDeletes
            ? new Set(explicitDeletes[schoolKey] || [])
            : new Set(
                currentData.students
                  .filter((s) => !importedMap.has(s.id))
                  .map((s) => s.id),
              );

          // Retain and update existing students not in deleteSet
          const retainedAndUpdated = currentData.students
            .filter((s) => !deleteSet.has(s.id))
            .map((existing) => {
              const updated = importedMap.get(existing.id);
              return updated ? { ...existing, ...updated } : existing;
            });

          // Add completely new students
          const existingIds = new Set(currentData.students.map((s) => s.id));
          const brandNew = schoolStudents.filter((s) => !existingIds.has(s.id));

          newStudents = [...retainedAndUpdated, ...brandNew];

          // Clean up registrations & placements for deleted students
          registrationsToKeep = currentData.registrations.filter(
            (r) => !deleteSet.has(r.studentId),
          );
          placementsToKeep = currentData.placements.filter(
            (p) => !deleteSet.has(p.studentId),
          );
        } else {
          // 'merge' (default): Add new students, update existing students, never delete
          const existingMap = new Map<string, Student>(
            currentData.students.map((s) => [s.id, s]),
          );
          schoolStudents.forEach((s) => {
            const existing = existingMap.get(s.id);
            if (existing) {
              existingMap.set(s.id, { ...existing, ...s });
            } else {
              existingMap.set(s.id, s);
            }
          });
          newStudents = Array.from(existingMap.values());
        }

        const updatedData: SchoolData = {
          ...currentData,
          students: newStudents,
          registrations: registrationsToKeep,
          placements: placementsToKeep,
        };

        updatedSchools[schoolKey] = updatedData;
        const replaceStudents = mode === "replace";
        persistSchoolChange(schoolKey, currentData, updatedData, {
          replaceStudents,
          ...(mode === "replace"
            ? { reviveStudentIds: newStudents.map((student) => student.id).filter(Boolean) }
            : {}),
          ...(mode === "sync_changes"
            ? { deleteStudentIds: diffDeletions(currentData, updatedData).deleteStudentIds }
            : {}),
        });
        try {
          localStorage.removeItem(`saved_students_${schoolKey}`);
        } catch (e) {}
      });

      // If a student is explicitly assigned to another existing school, move their
      // registrations with them. Never drop the registration on the floor.
      const studentTargetSchoolMap = new Map<string, string>();
      Object.entries(studentsBySchool).forEach(([sKey, sList]) => {
        sList.forEach((s) => {
          const target = canonicalSchoolKey(sKey) || sKey;
          if (updatedSchools[target]) studentTargetSchoolMap.set(s.id, target);
        });
      });

      Object.keys(updatedSchools).forEach((schoolKey) => {
        const schoolData = updatedSchools[schoolKey];
        if (!schoolData) return;

        const foreignStudentIds = new Set<string>();
        schoolData.students.forEach((s) => {
          const targetSchool = studentTargetSchoolMap.get(s.id);
          if (targetSchool && targetSchool !== schoolKey && updatedSchools[targetSchool]) {
            foreignStudentIds.add(s.id);
          }
        });

        if (foreignStudentIds.size > 0) {
          foreignStudentIds.forEach((studentId) => {
            const targetSchool = studentTargetSchoolMap.get(studentId);
            if (!targetSchool) return;
            const targetData = updatedSchools[targetSchool];
            const movingRegs = schoolData.registrations.filter((r) => r.studentId === studentId);
            const movingPlacements = schoolData.placements.filter((p) => p.studentId === studentId);
            const regMap = new Map<string, Registration>();
            (targetData.registrations || []).forEach((r) => regMap.set(r.studentId, r));
            movingRegs.forEach((r) => {
              const existing = regMap.get(r.studentId);
              regMap.set(r.studentId, existing ? preferRegistration(existing, r) : r);
            });
            const placementMap = new Map<string, Placement>();
            (targetData.placements || []).forEach((p) => placementMap.set(p.id, p));
            movingPlacements.forEach((p) => {
              if (!placementMap.has(p.id)) placementMap.set(p.id, p);
            });
            updatedSchools[targetSchool] = {
              ...targetData,
              registrations: Array.from(regMap.values()),
              placements: Array.from(placementMap.values()),
            };
          });

          const cleanedData: SchoolData = {
            ...schoolData,
            students: schoolData.students.filter((s) => !foreignStudentIds.has(s.id)),
            registrations: schoolData.registrations.filter((r) => !foreignStudentIds.has(r.studentId)),
            placements: schoolData.placements.filter((p) => !foreignStudentIds.has(p.studentId)),
          };
          updatedSchools[schoolKey] = cleanedData;
          persistSchoolChange(schoolKey, schoolData, cleanedData);
          const targetIds = new Set(
            Array.from(foreignStudentIds)
              .map((studentId) => studentTargetSchoolMap.get(studentId))
              .filter((id): id is string => !!id),
          );
          targetIds.forEach((targetId) => {
            persistSchoolChange(targetId, prev[targetId], updatedSchools[targetId]);
          });
        }
      });

      return updatedSchools;
    });
  };

  const addActivity = (activity: Activity) => {
    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      const updated = [...current.activities, activity];
      saveActivitiesToFirestore(currentSchoolId, updated);
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          activities: updated,
        },
      };
    });
  };

  const updateActivity = (id: string, updates: Partial<Activity>) => {
    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      const updated = current.activities.map((a) =>
        a.id === id ? { ...a, ...updates } : a,
      );
      saveActivitiesToFirestore(currentSchoolId, updated);
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          activities: updated,
        },
      };
    });
  };

  const deleteActivity = (id: string) => {
    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      const updated = current.activities.filter((a) => a.id !== id);
      saveActivitiesToFirestore(currentSchoolId, updated, { deleteActivityIds: [id] });
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          activities: updated,
        },
      };
    });
  };

  const importActivities = (
    imported: Activity[],
    modeOrReplace: ActivityImportMode | boolean = "sync_changes",
    options?: ImportActivitiesOptions,
  ) => {
    const mode: ActivityImportMode =
      typeof modeOrReplace === "boolean"
        ? modeOrReplace
          ? "replace"
          : "merge"
        : modeOrReplace;

    updateCurrentSchoolData((prev) => {
      if (mode === "replace") {
        return { ...prev, activities: imported };
      }

      const existingList = [...prev.activities];
      const normalize = (s: string) =>
        s.trim().toLowerCase().replace(/[\s_'"״\.\-]/g, "");

      const matchedExistingIds = new Set<string>();
      const finalActivities: Activity[] = [];

      imported.forEach((imp, idx) => {
        // 1. Try exact ID match
        let existing = existingList.find(
          (a) => a.id.toLowerCase() === imp.id.toLowerCase(),
        );

        // 2. Try match by normalized name + slot
        if (!existing) {
          existing = existingList.find(
            (a) =>
              !matchedExistingIds.has(a.id) &&
              normalize(a.name) === normalize(imp.name) &&
              a.slotNumber === imp.slotNumber,
          );
        }

        // 3. Try match by normalized name only
        if (!existing) {
          existing = existingList.find(
            (a) =>
              !matchedExistingIds.has(a.id) &&
              normalize(a.name) === normalize(imp.name),
          );
        }

        if (existing) {
          matchedExistingIds.add(existing.id);
          if (mode === "add_only") {
            finalActivities.push(existing);
          } else {
            // Update existing with imported changes (preserving stable existing ID)
            finalActivities.push({
              ...existing,
              ...imp,
              id: existing.id,
            });
          }
        } else {
          // New activity
          const newId =
            imp.id && !imp.id.startsWith("ACT-EX-")
              ? imp.id
              : `act-${imp.slotNumber || 1}-${Date.now().toString(36)}-${idx}`;
          finalActivities.push({
            ...imp,
            id: newId,
          });
        }
      });

      // Handle existing activities not in imported file
      const deleteIdSet = new Set(options?.deleteActivityIds || []);
      const unmatchedExisting = existingList.filter(
        (a) => !matchedExistingIds.has(a.id),
      );

      if (mode === "sync_changes") {
        unmatchedExisting.forEach((a) => {
          if (!deleteIdSet.has(a.id)) {
            finalActivities.push(a);
          }
        });
      } else if (mode === "merge" || mode === "add_only") {
        unmatchedExisting.forEach((a) => {
          finalActivities.push(a);
        });
      }

      const cleanedActivities = finalActivities.map((act) => {
        const isMolecular =
          act.name.includes("בישול מולקולרי") ||
          act.name.includes("שעתיים רצופות");
        const isDoubleSlot =
          isMolecular &&
          (act.slotNumber === 2 || act.startTime?.includes("שניה ושלישית"));
        const cleanSlotName = isDoubleSlot
          ? "שעה שניה ושלישית"
          : act.slotNumber === 1
            ? "שעה ראשונה"
            : act.slotNumber === 2
              ? "שעה שניה"
              : "שעה שלישית";
        return {
          ...act,
          startTime: cleanSlotName,
          endTime: "",
        };
      });

      return { ...prev, activities: cleanedActivities };
    });
  };

  const registerStudent = (
    data: Omit<Registration, "id" | "timestamp">,
  ): { success: boolean; message: string; regId?: string } => {
    const student = students.find((s) => s.id.trim() === data.studentId.trim());
    if (!student) {
      return {
        success: false,
        message:
          "תעודת זהות לא נמצאה ברשימת התלמידים הזכאים של מעגלים. אנא פנו למזכירות או לרכזת החוגים.",
      };
    }

    if (!student.isAuthorized) {
      return {
        success: false,
        message:
          "סטטוס הרשמת התלמיד אינו מאושר במערכת הזכאים. נא לפנות למזכירות מרכז מעגלים.",
      };
    }

    // Validate selections against First-Come First-Served capacities, duplicate subject rules, and 2-hour Molecular Cooking
    const validation = validateRegistrationSelections(
      currentSchoolId,
      activities,
      registrations,
      student,
      data.slot1Choice,
      data.slot2Choice,
      data.slot3Choice,
    );

    if (!validation.isValid) {
      return {
        success: false,
        message: validation.error || "שגיאה באימות בחירת החוגים.",
      };
    }

    const finalSlot3Choice = validation.adjustedSlot3Id || data.slot3Choice;

    const regId = `REG-MG-${Date.now().toString().slice(-6)}`;
    const newReg: Registration = {
      ...data,
      slot3Choice: finalSlot3Choice,
      slot1Backup: undefined,
      slot2Backup: undefined,
      slot3Backup: undefined,
      id: regId,
      timestamp: new Date().toISOString(),
    };

    // Instant placements for the 3 Friday slots (First-Come, First-Served)
    const act1 = activities.find((a) => a.id === data.slot1Choice);
    const act2 = activities.find((a) => a.id === data.slot2Choice);
    const act3 = activities.find((a) => a.id === finalSlot3Choice);

    const newPlacements: Placement[] = [
      {
        id: `PLC-${student.id}-SLOT1`,
        studentId: student.id,
        studentName: `${student.firstName} ${student.lastName}`,
        grade: student.grade,
        slotNumber: 1,
        placedActivityId: data.slot1Choice,
        status: "placed",
        priorityAchieved: 1,
        placementNotes: `שיבוץ מיידי ומאושר (כל הקודם זוכה) לחוג "${act1?.name || ""}"`,
        placedAt: new Date().toISOString(),
        isManualOverride: false,
      },
      {
        id: `PLC-${student.id}-SLOT2`,
        studentId: student.id,
        studentName: `${student.firstName} ${student.lastName}`,
        grade: student.grade,
        slotNumber: 2,
        placedActivityId: data.slot2Choice,
        status: "placed",
        priorityAchieved: 1,
        placementNotes: `שיבוץ מיידי ומאושר (כל הקודם זוכה) לחוג "${act2?.name || ""}"`,
        placedAt: new Date().toISOString(),
        isManualOverride: false,
      },
      {
        id: `PLC-${student.id}-SLOT3`,
        studentId: student.id,
        studentName: `${student.firstName} ${student.lastName}`,
        grade: student.grade,
        slotNumber: 3,
        placedActivityId: finalSlot3Choice,
        status: "placed",
        priorityAchieved: 1,
        placementNotes: `שיבוץ מיידי ומאושר (כל הקודם זוכה) לחוג "${act3?.name || ""}"`,
        placedAt: new Date().toISOString(),
        isManualOverride: false,
      },
    ];

    saveRegistrationToFirestore(currentSchoolId, newReg, newPlacements);

    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      const filteredRegistrations = current.registrations.filter(
        (r) => r.studentId !== data.studentId,
      );
      const filteredPlacements = current.placements.filter(
        (p) => p.studentId !== data.studentId,
      );
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          registrations: [newReg, ...filteredRegistrations],
          placements: [...newPlacements, ...filteredPlacements],
        },
      };
    });

    return {
      success: true,
      message: "ההרשמה ל-3 חוגי שישי נקלטה ושובצה בהצלחה במערכת!",
      regId,
    };
  };

  const deleteRegistration = (id: string) => {
    const reg = registrations.find((r) => r.id === id);
    deleteRegistrationFromFirestore(currentSchoolId, id, reg?.studentId);
    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          registrations: current.registrations.filter((r) => r.id !== id),
          placements: current.placements.filter((p) =>
            reg ? p.studentId !== reg.studentId : true,
          ),
        },
      };
    });
  };

  const updateRegistration = (updatedReg: Registration) => {
    const student = students.find((s) => s.id === updatedReg.studentId);
    const act1 = activities.find((a) => a.id === updatedReg.slot1Choice);
    const act2 = activities.find((a) => a.id === updatedReg.slot2Choice);
    const act3 = activities.find((a) => a.id === updatedReg.slot3Choice);

    const otherPlacements = placements.filter(
      (p) => p.studentId !== updatedReg.studentId,
    );

    const newPlacements: Placement[] = student
      ? [
          {
            id: `PLC-${student.id}-SLOT1`,
            studentId: student.id,
            studentName: `${student.firstName} ${student.lastName}`,
            grade: student.grade,
            slotNumber: 1,
            placedActivityId: updatedReg.slot1Choice,
            status: "placed",
            priorityAchieved: 1,
            placementNotes: `שיבוץ מעודכן לחוג "${act1?.name || ""}"`,
            placedAt: new Date().toISOString(),
            isManualOverride: true,
          },
          {
            id: `PLC-${student.id}-SLOT2`,
            studentId: student.id,
            studentName: `${student.firstName} ${student.lastName}`,
            grade: student.grade,
            slotNumber: 2,
            placedActivityId: updatedReg.slot2Choice,
            status: "placed",
            priorityAchieved: 1,
            placementNotes: `שיבוץ מעודכן לחוג "${act2?.name || ""}"`,
            placedAt: new Date().toISOString(),
            isManualOverride: true,
          },
          {
            id: `PLC-${student.id}-SLOT3`,
            studentId: student.id,
            studentName: `${student.firstName} ${student.lastName}`,
            grade: student.grade,
            slotNumber: 3,
            placedActivityId: updatedReg.slot3Choice,
            status: "placed",
            priorityAchieved: 1,
            placementNotes: `שיבוץ מעודכן לחוג "${act3?.name || ""}"`,
            placedAt: new Date().toISOString(),
            isManualOverride: true,
          },
        ]
      : [];

    updateRegistrationInFirestore(currentSchoolId, updatedReg, newPlacements);

    setSchools((prev) => {
      const current = prev[currentSchoolId];
      if (!current) return prev;
      return {
        ...prev,
        [currentSchoolId]: {
          ...current,
          registrations: current.registrations.map((r) =>
            r.id === updatedReg.id ? updatedReg : r,
          ),
          placements: [...otherPlacements, ...newPlacements],
        },
      };
    });
  };

  const importRegistrations = (
    importedRegs: Registration[],
    targetSchoolId?: string,
  ): { success: boolean; count: number } => {
    if (!importedRegs || importedRegs.length === 0) {
      return { success: false, count: 0 };
    }

    const defaultSchoolKey = targetSchoolId || currentSchoolId;

    setSchools((prev) => {
      const updated: Record<string, SchoolData> = { ...prev };

      // Group registrations by school if possible
      const regsBySchool: Record<string, Registration[]> = {};
      importedRegs.forEach((r) => {
        let sKey = defaultSchoolKey;
        for (const [k, sData] of Object.entries(prev)) {
          const typedData = sData as SchoolData;
          if (typedData.students && typedData.students.some((s) => s.id === r.studentId)) {
            sKey = k;
            break;
          }
        }
        if (!regsBySchool[sKey]) regsBySchool[sKey] = [];
        regsBySchool[sKey].push(r);
      });

      Object.entries(regsBySchool).forEach(([sKey, regsList]) => {
        const currentData = updated[sKey] || updated[defaultSchoolKey];
        if (!currentData) return;

        const regMap = new Map<string, Registration>();
        (currentData.registrations || []).forEach((r) => regMap.set(r.studentId, r));
        regsList.forEach((r) => {
          const existing = regMap.get(r.studentId);
          regMap.set(r.studentId, existing ? preferRegistration(existing, r) : r);
        });

        const mergedRegs = Array.from(regMap.values());
        const placementMap = new Map<string, Placement>();
        (currentData.placements || []).forEach((p) => placementMap.set(p.id, p));
        generatePlacementsForRegistrations(regsList).forEach((p) => placementMap.set(p.id, p));

        const nextData: SchoolData = {
          ...currentData,
          registrations: mergedRegs,
          placements: Array.from(placementMap.values()),
        };
        updated[sKey] = nextData;
        persistSchoolChange(sKey, currentData, nextData);
      });

      return updated;
    });

    return { success: true, count: importedRegs.length };
  };

  const importFullWorkbook = (data: {
    students?: Student[];
    activities?: Activity[];
    registrations?: Registration[];
    placements?: Placement[];
    targetSchoolId?: string;
  }): { success: boolean; studentsCount: number; regsCount: number; actsCount: number } => {
    const sId = canonicalSchoolKey(data.targetSchoolId || currentSchoolId) || currentSchoolId;
    const sCount = data.students?.length || 0;
    const rCount = data.registrations?.length || 0;
    const aCount = data.activities?.length || 0;

    setSchools((prev) => {
      const current = prev[sId];
      if (!current) return prev;
      const incoming: SchoolData = {
        ...current,
        students: data.students && data.students.length > 0 ? data.students.map((student) => ({
          ...student,
          schoolId: sId,
          schoolName: student.schoolName || current.school.name,
        })) : current.students,
        activities: data.activities && data.activities.length > 0 ? data.activities : current.activities,
        registrations: data.registrations && data.registrations.length > 0 ? data.registrations : current.registrations,
        placements: data.placements && data.placements.length > 0 ? data.placements : current.placements,
      };
      const merged = mergeSchoolSnapshot(current, incoming).data as SchoolData;
      if ((!data.placements || data.placements.length === 0) && data.registrations && data.registrations.length > 0) {
        const placementMap = new Map<string, Placement>();
        (merged.placements || []).forEach((p) => placementMap.set(p.id, p));
        generatePlacementsForRegistrations(data.registrations).forEach((p) => placementMap.set(p.id, p));
        merged.placements = Array.from(placementMap.values());
      }
      persistSchoolChange(sId, current, merged, {
        reviveStudentIds: (data.students || []).map((student) => student.id).filter(Boolean),
        reviveRegistrationStudentIds: (data.registrations || [])
          .map((reg) => reg.studentId)
          .filter(Boolean),
        reviveRegistrationIds: (data.registrations || []).map((reg) => reg.id).filter(Boolean),
      });
      return { ...prev, [sId]: merged };
    });

    return {
      success: true,
      studentsCount: sCount,
      regsCount: rCount,
      actsCount: aCount,
    };
  };

  const restoreFullBackup = (
    incoming: Record<string, SchoolData>,
  ): { success: boolean; schools: number; registrations: number; students: number } => {
    const folded = foldAliasSchools(incoming as Record<string, SchoolSnapshot>) as Record<string, SchoolData>;
    let schoolsTouched = 0;
    let registrations = 0;
    let students = 0;
    setSchools((prev) => {
      const updated: Record<string, SchoolData> = { ...prev };
      Object.entries(folded).forEach(([rawId, snapshot]) => {
        if (!snapshot) return;
        const id = canonicalSchoolKey(snapshot.school?.id || rawId) || rawId;
        const local = updated[id];
        const client: SchoolData = {
          school: { ...(local?.school || snapshot.school), ...(snapshot.school || {}), id },
          students: snapshot.students || [],
          activities: snapshot.activities || [],
          registrations: snapshot.registrations || [],
          placements: snapshot.placements || [],
        };
        const merged = (local ? mergeSchoolSnapshot(local, client).data : client) as SchoolData;
        updated[id] = merged;
        persistSchoolChange(id, local, merged, {
          reviveStudentIds: (snapshot.students || []).map((student) => student.id).filter(Boolean),
          reviveRegistrationStudentIds: (snapshot.registrations || [])
            .map((reg) => reg.studentId)
            .filter(Boolean),
          reviveRegistrationIds: (snapshot.registrations || []).map((reg) => reg.id).filter(Boolean),
        });
        schoolsTouched += 1;
        registrations += snapshot.registrations?.length || 0;
        students += snapshot.students?.length || 0;
      });
      return updated;
    });
    return {
      success: schoolsTouched > 0,
      schools: schoolsTouched,
      registrations,
      students,
    };
  };

  const runPlacementEngine = (config?: AlgorithmConfig): MatchingResult => {
    const result = runMatchingAlgorithm(
      students,
      activities,
      registrations,
      config,
    );
    setExecutionLogs(result.logs);
    setLastSummary(result.summary);

    updateCurrentSchoolData((prev) => ({
      ...prev,
      placements: result.placements,
    }));

    return result;
  };

  const manualOverridePlacement = (
    studentId: string,
    slotNumber: 1 | 2 | 3,
    activityId: string | null,
    status: PlacementStatus,
    notes: string,
  ) => {
    const student = students.find((s) => s.id === studentId);
    if (!student) return;

    updateCurrentSchoolData((prev) => {
      const existing = prev.placements.find(
        (p) => p.studentId === studentId && p.slotNumber === slotNumber,
      );
      const updatedPlacement: Placement = {
        id: existing ? existing.id : `PLC-${studentId}-SLOT${slotNumber}`,
        studentId,
        studentName: `${student.firstName} ${student.lastName}`,
        grade: student.grade,
        slotNumber,
        placedActivityId: activityId,
        status,
        priorityAchieved: existing?.priorityAchieved || null,
        placementNotes: notes,
        placedAt: new Date().toISOString(),
        isManualOverride: true,
      };

      const otherPlacements = prev.placements.filter(
        (p) => !(p.studentId === studentId && p.slotNumber === slotNumber),
      );

      return {
        ...prev,
        placements: [updatedPlacement, ...otherPlacements],
      };
    });
  };

  const clearPlacements = () => {
    updateCurrentSchoolData((prev) => ({
      ...prev,
      placements: [],
    }), { replacePlacements: true });
    setExecutionLogs([]);
    setLastSummary(null);
  };

  const resetCurrentSchoolToDefaults = () => {
    const original =
      INITIAL_SCHOOLS[currentSchoolId] ||
      INITIAL_SCHOOLS["sch-ben-shemen"] ||
      Object.values(INITIAL_SCHOOLS)[0];
    const fresh = JSON.parse(JSON.stringify(original));
    fresh.activities = getOfficialActivitiesForSchool(currentSchoolId);
    updateCurrentSchoolData(() => fresh, {
      replaceStudents: true,
      replaceActivities: true,
      replaceRegistrations: true,
      replacePlacements: true,
    });
    setExecutionLogs([]);
    setLastSummary(null);
  };

  const restoreOfficialActivities = async (schoolId?: string) => {
    const targetId = schoolId || currentSchoolId;
    setSchools((prev) => {
      const updated: Record<string, SchoolData> = { ...prev };
      if (targetId && updated[targetId]) {
        updated[targetId] = {
          ...updated[targetId],
          activities: getOfficialActivitiesForSchool(targetId),
        };
        persistSchoolChange(targetId, prev[targetId], updated[targetId], {
          replaceActivities: true,
        });
      } else {
        Object.keys(updated).forEach((k) => {
          const next = {
            ...updated[k],
            activities: getOfficialActivitiesForSchool(k),
          };
          persistSchoolChange(k, updated[k], next, { replaceActivities: true });
          updated[k] = next;
        });
      }
      return enrichAllSchoolsActivities(updated);
    });
  };

  return (
    <SchoolContext.Provider
      value={{
        schools,
        currentSchoolId,
        currentSchool,
        coordinator,
        students,
        activities,
        registrations,
        placements,
        executionLogs,
        lastSummary,
        isContactModalOpen,
        setIsContactModalOpen,
        customGlobalLogoUrl,
        updateLogo,
        isAdminAuthenticated,
        loginAdmin,
        logoutAdmin,
        updateAdminPassword,
        selectSchool,
        addNewSchool,
        updateSchoolInfo,
        updateCoordinatorInfo,
        updateSchoolCoordinator,
        updateFridaySlots,
        addStudent,
        updateStudent,
        deleteStudent,
        deleteStudents,
        clearAllStudents,
        importStudents,
        addActivity,
        updateActivity,
        deleteActivity,
        importActivities,
        registerStudent,
        updateRegistration,
        deleteRegistration,
        importRegistrations,
        importFullWorkbook,
        runPlacementEngine,
        manualOverridePlacement,
        clearPlacements,
        resetCurrentSchoolToDefaults,
        restoreOfficialActivities,
        syncStatus,
        syncErrorMessage,
        refreshFromCloud,
        uploadLocalDataToCloud,
        executeDeepCacheRecovery,
        restoreFullBackup,
      }}
    >
      {children}
    </SchoolContext.Provider>
  );
};

export const useSchool = () => {
  const context = useContext(SchoolContext);
  if (!context) {
    throw new Error("useSchool must be used within a SchoolProvider");
  }
  return context;
};
